[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
number_setting = "4givkSHuinrWG49gm8xs1xPmZ5E6E7haMFwxyLdw23Ct"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
